using Watchroom.Core;

static class MediaCacheFixture
{
    public static async Task Run(Action<bool, string> check)
    {
        var source = new Source();
        var cached = new CachedMediaSource(source, MediaStreaming.ChunkBytes * 2);
        var first = await cached.ReadAsync(100, 40000, default);
        check(first.SequenceEqual(source.Bytes.AsSpan(100, 40000).ToArray()), "unaligned cached ranges preserve exact media bytes");
        var reads = source.Reads;
        await cached.ReadAsync(500, 1000, default);
        check(source.Reads == reads, "nearby backward seek reuses cached media without another transfer");
        await cached.ReadAsync(MediaStreaming.ChunkBytes * 2, 100, default);
        await cached.ReadAsync(0, 100, default);
        check(source.Reads == reads + 1, "LRU media cache retains the recent block within its memory bound");
        await cached.ReadAsync(MediaStreaming.ChunkBytes, 100, default);
        check(source.Reads == reads + 2, "evicted media blocks are fetched again instead of retaining the entire movie");
        source = new Source { Delay = true }; cached = new CachedMediaSource(source);
        using var cancel = new CancellationTokenSource();
        var abandoned = cached.ReadAsync(0, 100, cancel.Token);
        var active = cached.ReadAsync(100, 100, default);
        cancel.Cancel();
        try { await abandoned; } catch (OperationCanceledException) { }
        source.Release.TrySetResult();
        check((await active).SequenceEqual(source.Bytes.AsSpan(100, 100).ToArray()) && source.Reads == 1 && source.Canceled == 0,
            "canceling an obsolete seek preserves a shared block needed by another reader");
        source = new Source { Delay = true }; cached = new CachedMediaSource(source);
        using var cancelAll = new CancellationTokenSource();
        abandoned = cached.ReadAsync(0, 100, cancelAll.Token);
        await source.Started.Task.WaitAsync(TimeSpan.FromSeconds(2)); cancelAll.Cancel();
        try { await abandoned; } catch (OperationCanceledException) { }
        await source.CancellationSeen.Task.WaitAsync(TimeSpan.FromSeconds(2));
        source.Release.TrySetResult();
        check((await cached.ReadAsync(0, 100, default)).Length == 100 && source.Reads == 2,
            "last canceled consumer stops stale transfer and a new seek can retry immediately");
    }
    private sealed class Source : IMediaSource
    {
        public byte[] Bytes = Enumerable.Range(0, MediaStreaming.ChunkBytes * 4).Select(i => (byte)(i % 251)).ToArray();
        public SharedMedia Media => new("cache-test", "Generated bytes", Bytes.Length, ".bin");
        public int Reads, Canceled;
        public bool Delay;
        public TaskCompletionSource Release = new(TaskCreationOptions.RunContinuationsAsynchronously);
        public TaskCompletionSource Started = new(TaskCreationOptions.RunContinuationsAsynchronously);
        public TaskCompletionSource CancellationSeen = new(TaskCreationOptions.RunContinuationsAsynchronously);
        public async Task<byte[]> ReadAsync(long offset, int count, CancellationToken ct)
        {
            Interlocked.Increment(ref Reads); Started.TrySetResult();
            try
            {
                if (Delay) await Release.Task.WaitAsync(ct);
                ct.ThrowIfCancellationRequested();
                return Bytes.AsSpan((int)offset, count).ToArray();
            }
            catch (OperationCanceledException) { Interlocked.Increment(ref Canceled); CancellationSeen.TrySetResult(); throw; }
        }
    }
}
