using System.Diagnostics;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Channels;
using Watchroom.Core;

static class RelayStreamingFixture
{
    public static async Task Run(string server, Action<bool, string> check)
    {
        using var timeout = new CancellationTokenSource(TimeSpan.FromMinutes(3));
        using var http = new HttpClient { BaseAddress = new Uri(server), Timeout = TimeSpan.FromSeconds(20) };
        var created = await http.PostAsJsonAsync("/sessions", new { type = "create", text = "Transport regression" }, timeout.Token);
        created.EnsureSuccessStatusCode();
        var session = await created.Content.ReadFromJsonAsync<JsonElement>(timeout.Token);
        http.DefaultRequestHeaders.Authorization = new("Bearer", session.GetProperty("token").GetString());
        try
        {
            var events = await http.GetFromJsonAsync<JsonElement>("/session?since=0", timeout.Token);
            var welcome = events.GetProperty("events").EnumerateArray().Select(e => e.GetProperty("message")).First(e => e.GetProperty("type").GetString() == "welcome");
            var identity = Wire.Read<Welcome>(welcome.GetProperty("data").GetString()!);
            check(identity.IceServers.Any(s => s.StartsWith("turn:")), "live service provides relay credentials");
            using var host = new PeerTransport(identity.IceServers, true);
            using var guest = new PeerTransport(identity.IceServers, true);
            var signals = Channel.CreateUnbounded<(PeerTransport Peer, string Type, string Data)>();
            host.Signal += (type, data) => signals.Writer.TryWrite((guest, type, data));
            guest.Signal += (type, data) => signals.Writer.TryWrite((host, type, data));
            var pump = Task.Run(async () => { await foreach (var s in signals.Reader.ReadAllAsync(timeout.Token)) s.Peer.ReceiveSignal(s.Type, s.Data); });
            var source = new GeneratedSource(); host.ResolveMedia = id => id == source.Media.Id ? source : null;
            host.StartOffer();
            await Task.WhenAll(host.Ready, guest.Ready, host.ControlReady, guest.ControlReady).WaitAsync(TimeSpan.FromSeconds(35), timeout.Token);
            var received = new System.Collections.Concurrent.ConcurrentDictionary<long, TaskCompletionSource>();
            guest.ControlMessage += message => { if (received.TryGetValue(message.Number, out var done)) done.TrySetResult(); };
            var slowest = 0L;
            var controls = Task.Run(async () => {
                for (var index = 1; index <= 15; index++) {
                    var done = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously); received[index] = done;
                    var clock = Stopwatch.StartNew(); host.SendControl(new("notice", Number: index));
                    await done.Task.WaitAsync(TimeSpan.FromSeconds(30), timeout.Token);
                    slowest = Math.Max(slowest, clock.ElapsedMilliseconds); await Task.Delay(200, timeout.Token);
                }
            });
            var timer = Stopwatch.StartNew();
            // Continuous movie-sized traffic, with concurrent playback commands.
            var readers = Enumerable.Range(0, MediaStreaming.Window).Select(async reader => {
                for (var offset = (long)reader * MediaStreaming.ChunkBytes; offset < source.Media.Length; offset += MediaStreaming.Window * MediaStreaming.ChunkBytes) {
                    var count = (int)Math.Min(MediaStreaming.ChunkBytes, source.Media.Length - offset);
                    var bytes = await guest.ReadAsync(source.Media.Id, offset, count, timeout.Token);
                    if (bytes.Length != count || !bytes.SequenceEqual(GeneratedSource.Bytes(offset, count))) throw new IOException("Corrupted relay range");
                }
            });
            await Task.WhenAll(readers); await controls;
            check(host.UsesIsolatedMedia && guest.UsesIsolatedMedia, "media uses an independent connection on both peers");
            Console.WriteLine($"Relay transfer: {source.Media.Length * 8 / timer.Elapsed.TotalSeconds / 1000000:F2} Mbps; slowest control {slowest} ms");
            check(slowest < 3000, "playback controls remain responsive during continuous relay transfer");
            await StreamingAudioFixture.Run(Path.Combine("artifacts/relay-audio", Guid.NewGuid().ToString("N")), check, iceServers: identity.IceServers, relayOnly: true);
            timeout.Cancel(); try { await pump; } catch (OperationCanceledException) { }
        }
        finally { await http.DeleteAsync("/session"); }
    }
    private sealed class GeneratedSource : IMediaSource
    {
        public SharedMedia Media { get; } = new("relay-test", "Generated bytes", 12 * 1024 * 1024, ".bin");
        public static byte[] Bytes(long offset, int count) => Enumerable.Range(0, count).Select(i => (byte)((offset + i) * 31 + (offset + i) / 251)).ToArray();
        public Task<byte[]> ReadAsync(long offset, int count, CancellationToken ct) => Task.FromResult(Bytes(offset, count));
    }
}
